# Generated by Django 5.2.4 on 2025-08-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_before',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('use', 'Use')], default='transaction', max_length=15),
        ),
    ]
